package:
  name: mlir-graphblas
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'unknown') }}

source:
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)|int }}
  string: py_{{GIT_DESCRIBE_HASH}}_{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  noarch: python

requirements:
  host:
    - python=3.8
    - numpy
    - cython
    - metagraph::mlir

  run:
    - python=3.8
    - metagraph::mlir
    - pymlir
    - llvmlite
    - pygments
    - donfig
    - panel
    - numpy
    - bokeh<2.3  # temp restriction until panel/bokeh bugs are worked out

test:
  requires:
    - pytest
    - pytest-cov
    - coverage

  commands:
    - pytest --pyargs mlir_graphblas.tests

about:
  home: https://github.com/metagraph-dev/mlir-graphblas
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'MLIR dialect for GraphBLAS'
  description: |
      MLIR dialect for GraphBLAS + Python tools
  dev_url: https://github.com/metagraph-dev/mlir-graphblas
